name: Create release

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  RUBY_CC_VERSION: "3.2"  # Build with 3.2, uses stable ABI

jobs:
  build-gems:
    name: Build gem (${{ matrix.platform }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - platform: arm64-darwin
            os: macos-latest  # M1 runner
            rake_task: "native:rs_floating_duration gem"
          - platform: x86_64-linux
            os: ubuntu-latest
            rake_task: "native[x86_64-linux]"
          - platform: aarch64-linux
            os: ubuntu-latest # rb-sys:aarch64-linux was built for amd64 platform (by mistake?)
            rake_task: "native:rs_floating_duration gem"
          - platform: ruby
            os: ubuntu-latest
            rake_task: build
    steps:
      - uses: actions/checkout@v7

      - uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.platform }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust
        if: matrix.platform != 'ruby'
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Build gem
        env:
          CARGO_TARGET_DIR: target/${{ matrix.platform }}
        run: |
          set -o pipefail
          bundle exec ruby -e 'puts RUBY_PLATFORM'
          bundle exec rake --trace ${{ matrix.rake_task }}
          echo "gem_filename=$(ls -t pkg/*.gem|head -1|xargs basename)" >> "$GITHUB_ENV"

      - uses: actions/upload-artifact@v7
        with:
          name: ${{ env.gem_filename }}
          path: pkg/${{ env.gem_filename }}
