name: Create release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - build-separate-gems

env:
  RUBY_CC_VERSION: "3.2"  # Build with 3.2, uses stable ABI

jobs:
  build-gems:
    name: Build gem (${{ matrix.platform }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - platform: arm64-darwin
            os: macos-latest  # M1 runner
            rake_task: "native[arm64-darwin]"
          - platform: x86_64-linux
            os: ubuntu-latest
            rake_task: "native[x86_64-linux]"
          - platform: aarch64-linux
            os: ubuntu-latest
            rake_task: "native[aarch64-linux]"
          - platform: ruby
            os: ubuntu-latest
            rake_task: build
    steps:
      - uses: actions/checkout@v6

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.platform }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust
        if: matrix.platform != 'ruby'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Build gem
        env:
          CARGO_TARGET_DIR: target/${{ matrix.platform }}
        run: |
          set -o pipefail
          bundle exec rake ${{ matrix.rake_task }} | tee build.log
          gem_filename=$(grep -oP '(?<=File: ).*\.gem$' build.log | tail -1)
          echo "gem_filename=$gem_filename" >> "$GITHUB_ENV"
      
      - uses: actions/upload-artifact@v5
        with:
          name: gem-${{ matrix.platform }}
          path: pkg/${{ env.gem_filename }}
